import type { KnowledgeArticle } from "@/lib/types";

function topic(
  id: string,
  slug: string,
  title: string,
  summary: string,
  category: string,
  details: NonNullable<KnowledgeArticle["details"]>,
  sourceIds: string[] = []
): KnowledgeArticle {
  return {
    id,
    slug,
    title,
    summary,
    content: details.whyImportant,
    sourceIds,
    reviewStatus: "needs_scholar_review",
    category,
    details,
  };
}

export const wissenTopics: KnowledgeArticle[] = [
  topic("w-janazah", "janazah-wuensche", "Janazah-Wünsche", "Deine Bestattungswünsche sind eine Amanah — dokumentiere sie, bevor andere ratlos sind.", "janazah", {
    whyImportant: "Janazah ist die letzte gemeinschaftliche Pflicht deiner Familie und der Ummah dir gegenüber. Wenn du deine Wünsche nicht festhältst, entscheiden Angehörige unter Schock, oft nach Kultur statt nach Islam — oder nach deutschen Standardabläufen.",
    ifMissing: "Verzögerungen, Streit über Überführung vs. Beisetzung, falsche Kontakte, teure Zusatzleistungen, die du nicht wolltest. Die Familie fühlt sich schuldig, obwohl sie ratlos war.",
    prepareItems: ["Beisetzung in Deutschland oder Überführung ins Herkunftsland", "Bevorzugter Bestatter und Moschee/Imam-Kontakt", "Ghusl-Wünsche (wer darf waschen, Geschlechterregeln)", "Kafan-Anzahl und Beschaffung", "Janazah-Gebet: wo und von wem", "Keine unnötigen kulturellen Trauerfeiern, die belasten"],
    documents: ["Schriftliche Janazah-Wünsche", "Bestatter-Vertrag oder Kontaktdaten", "Reisepass/Kopien bei Überführungswunsch", "Versicherungs-/Kostenklärung"],
    safeStorage: "In Mein Wille, zusätzlich Ausdruck beim Bestatter und bei einer Vertrauensperson. Nicht nur im Kopf einer Person.",
    tellFamily: "Wo der Ordner liegt, wer den Bestatter anruft, dass islamische Grundsätze Vorrang haben — und dass sie nicht alles allein entscheiden müssen.",
    commonMistakes: ["Mündliche Absprachen ohne Dokument", "Nur kulturelle Traditionen statt islamischer Mindestanforderungen", "Kein Bestatter-Kontakt in Deutschland", "Wünsche erst im Sterbebett — dann oft zu spät"],
    nextStepLabel: "Janazah-Wünsche jetzt festhalten",
    nextStepHref: "/dashboard/janazah",
  }, ["hadith-bukhari-janazah-1315", "hadith-muslim-janazah-944c"]),
  topic("w-ghusl", "ghusl-kafan", "Ghusl & Kafan", "Totenwaschung und Leichentuch sind zentrale islamische Rituale — plane sie konkret.", "ghusl-kafan", {
    whyImportant: "Ghusl und Kafan sind Teil der Würde des Verstorbenen. In Deutschland übernehmen oft Moschee, Bestatter oder Familie — wer was darf, muss vorher geklärt sein.",
    ifMissing: "Falsche Personen waschen, Verzögerung, unnötige Kosten, familiäre Konflikte über Geschlechterregeln, Unsicherheit im Krankenhaus.",
    prepareItems: ["Wer Ghusl durchführen soll (gleichgeschlechtlich, muslimisch)", "Ob Moschee/Bestatter übernimmt", "Kafan-Material beschaffen lassen", "Schamgrenzen und Würde betonen", "Kontakt für Notfall nachts/Wochenende"],
    documents: ["Schriftliche Ghusl/Kafan-Wünsche", "Moschee-Kontakt", "Bestatter-Leistungsbeschreibung"],
    safeStorage: "Mein Wille + Kopie bei Moschee/Bestatter.",
    tellFamily: "Dass Ghusl islamisch prioritär ist, wer angerufen wird, und dass sie nicht aus Scham deutsche Standardprozeduren akzeptieren müssen, ohne zu fragen.",
    commonMistakes: ["Keine Klärung bei Meinungsunterschieden", "Kafan nicht vorab organisiert", "Annahme, Krankenhaus regelt alles islamisch"],
    nextStepLabel: "Ghusl & Kafan dokumentieren",
    nextStepHref: "/dashboard/ghusl-kafan",
  }),
  topic("w-bestattung", "bestattung-ueberfuehrung", "Bestattung & Überführung", "Deutschland oder Heimat — beides braucht Vorplanung, Geld und klare Vollmachten.", "bestattung", {
    whyImportant: "Rechtliche Fristen, Kosten, Visa, Flugtransport und Familienmeinungen kollidieren oft innerhalb von 48 Stunden nach dem Tod.",
    ifMissing: "Teure Eil-Überführung, Streit zwischen Geschwistern, falsche Annahmen über Versicherung, Verzögerung der Janazah.",
    prepareItems: ["Entscheidung: Beisetzung DE vs. Überführung", "Kostenrahmen und wer zahlt", "Islamisches Friedhof-Grundstück oder muslimischer Friedhof", "Kontakt Auslandsbehörde/Botschaft", "Reise-/Rückführungsversicherung prüfen"],
    documents: ["Bestattungsvorsorgevertrag optional", "Reisepass-Kopien", "Heirats-/Geburtsurkunden für Überführung", "Vollmacht für Vertrauensperson"],
    safeStorage: "Ordner physisch + digital, Vertrauensperson informiert.",
    tellFamily: "Klare Entscheidung, Budget-Rahmen, wer unterschreibt, dass Janazah-Gebet nicht monatelang warten soll.",
    commonMistakes: ["Kein Geld für Überführung", "Nur mündlich 'nach Hause'", "Kein Friedhof recherchiert", "Versicherung nicht geprüft"],
    nextStepLabel: "Bestattungswünsche festhalten",
    nextStepHref: "/dashboard/bestattung",
  }),
  topic("w-pv", "patientenverfuegung", "Patientenverfügung", "Wenn du nicht mehr sprechen kannst, entscheidet sonst oft das Krankenhaus — nicht dein Islam und nicht deine Familie.", "patientenverfuegung", {
    whyImportant: "Ohne Patientenverfügung greifen deutsche Standardprotokolle. Für Muslime kann das Medikamente, Beatmung oder Behandlungsabbruch betreffen — fachlich mit Arzt klären, aber vorher dokumentieren.",
    ifMissing: "Unerwünschte Maßnahmen, Familie ohne Stimme, Konflikte zwischen Ärzten und Angehörigen, zusätzlicher seelischer Schmerz.",
    prepareItems: ["Welche Behandlungen du ablehnst oder wünschst", "Schmerztherapie vs. Lebensverlängerung — mit Arzt besprechen", "Organspende-Haltung", "Imam/Seelsorge im Krankenhaus", "Aktualisierung alle 2–3 Jahre"],
    documents: ["Patientenverfügung (schriftlich, unterschrieben)", "Kopie für Vorsorgevollmacht-Inhaber", "Kopie in Notfallmappe"],
    safeStorage: "Notfallmappe zu Hause, Foto am Handy der Vertrauensperson, ggf. Arztakte.",
    tellFamily: "Dass die Patientenverfügung existiert, wo sie liegt, und dass sie deinen Wunsch vertreten sollen — nicht ihre Angst.",
    commonMistakes: ["Vorlage aus Internet ohne Anpassung", "Veraltete Version", "Nur online ohne Ausdruck", "Keine Kopie im Krankenfall"],
    nextStepLabel: "Medizinische Wünsche dokumentieren",
    nextStepHref: "/dashboard/krankheit",
  }, ["official-patientenverfuegung"]),
  topic("w-vollmacht", "vorsorgevollmacht", "Vorsorgevollmacht", "Wer darf für dich unterschreiben, wenn du es nicht kannst?", "vorsorgevollmacht", {
    whyImportant: "Bank, Krankenhaus, Vermieter — ohne Vollmacht kann selbst dein Ehepartner nicht handeln. Das trifft Muslime in Deutschland besonders hart bei schnellen Entscheidungen.",
    ifMissing: "Betreuungsgericht muss einspringen, Verzögerung, hohe Kosten, falsche Person entscheidet.",
    prepareItems: ["Vertrauensperson benennen (Ehepartner, Geschwister, Freund)", "Ersatzperson festlegen", "Umfang: Gesundheit, Finanzen, Wohnung", "Notarielle Beglaubigung prüfen", "Kopien verteilen"],
    documents: ["Vorsorgevollmacht (notariell oder schriftlich je nach Umfang)", "Kopie Personalausweis der Bevollmächtigten"],
    safeStorage: "Original sicher, Kopien bei Bevollmächtigten und im Ordner.",
    tellFamily: "Wer bevollmächtigt ist, was die Person darf, und dass sie im Notfall sofort die Vollmacht vorlegen soll.",
    commonMistakes: ["Nur mündlich 'du entscheidest'", "Keine Ersatzperson", "Vollmacht zu alt", "Nicht beim Krankenhaus hinterlegt"],
    nextStepLabel: "Vorsorgevollmacht vorbereiten",
    nextStepHref: "/dashboard/vollmacht",
  }),
  topic("w-betreuung", "betreuungsverfuegung", "Betreuungsverfügung", "Du kannst mitbestimmen, wer Betreuer wird — sonst entscheidet das Gericht.", "betreuung", {
    whyImportant: "Bei dauerhafter Entscheidungsunfähigkeit ohne Vorsorge greift deutsche Betreuungsrecht. Eine Betreuungsverfügung gibt dir Mitsprache.",
    ifMissing: "Fremde Betreuung, Verzögerung, Familie außen vor, Entscheidungen gegen deine Werte.",
    prepareItems: ["Wunschperson für Betreuung", "Personen, die ausgeschlossen werden sollen", "Wünsche zu Wohnort/Pflege", "Abstimmung mit Vorsorgevollmacht"],
    documents: ["Betreuungsverfügung", "Optional Vorsorgevollmacht ergänzend"],
    safeStorage: "Mit Vorsorgeunterlagen, Kopie an Wunschperson.",
    tellFamily: "Dass du jemanden vorgeschlagen hast und sie das Gericht unterstützen sollen.",
    commonMistakes: ["Verwechslung mit Patientenverfügung", "Keine Abstimmung zwischen Dokumenten"],
    nextStepLabel: "Betreuungswünsche festhalten",
    nextStepHref: "/dashboard/betreuung",
  }),
  topic("w-testament", "testament-erbe", "Testament & Erbe", "Islamisches Erbe und deutsches Erbrecht kollidieren — ohne Planung leiden Angehörige doppelt.", "testament", {
    whyImportant: "Allah hat Erbteile festgelegt. In Deutschland brauchst du oft ein Testament/Erbvertrag, damit islamische Verteilung und Pflichtteile zusammenpassen — das ist Angelegenheit für Fachleute, aber du musst vorbereiten.",
    ifMissing: "Streit unter Erben, Sünde durch Ungerechtigkeit, Rechtsunsicherheit, Verlust von Vermögen an falsche Stellen.",
    prepareItems: ["Vermögensübersicht", "Erben nach islamischem Recht listen", "Waṣiyya (max. 1/3) für Nicht-Erben planen — fachlich prüfen", "Islamischen Berater/Anwalt einschalten", "Schulden und Vermächtnisse vor Erbverteilung bedenken (Qur'an, fachlich prüfen)"],
    documents: ["Testament/Erbvertrag", "Vermögensliste", "Schuldenliste", "Heiratsvertrag falls relevant"],
    safeStorage: "Notar/Safe + Vertrauensperson weiß Bescheid.",
    tellFamily: "Dass ein Plan existiert, wer Erbe ist, dass Vermächtnisse und Schulden vor der Verteilung bedacht werden müssen, und dass sie fachliche Hilfe holen sollen — nicht selbst interpretieren.",
    commonMistakes: ["Haus an einen Sohn 'geben' ohne Erbplan", "Waṣiyya über 1/3", "Kein deutscher Testamentsentwurf", "Schulden verschweigen"],
    nextStepLabel: "Erbe & Testament vorbereiten",
    nextStepHref: "/dashboard/testament",
  }, ["quran-nisa-4-11", "quran-nisa-4-12", "hadith-wasiyyah-third"]),
  topic("w-schulden", "schulden-amanah", "Schulden & Amanah", "Unbezahlte Schulden und anvertraute Güter sind eine Amanah — sie überleben deinen Tod.", "schulden", {
    whyImportant: "Offene Schulden und anvertraute Güter (Amanah) können Familie und Community belasten. Die Überlieferung verdeutlicht, wie ernst Schulden genommen wurden — ohne dass diese App individuelle religiöse oder erbrechtliche Regeln ersetzt.",
    ifMissing: "Familie zahlt aus Unwissenheit, Streit, Belastung durch vergessene Schulden, verlorenes Vertrauen in der Community.",
    prepareItems: ["Alle Schulden listen (Geld, geliehene Sachen)", "An wen, Betrag, Frist", "Amanah: anvertraute Werte, Waqf, Gelübde", "Plan: wie Schulden aus dem Nachlass geordnet werden — mit Anwalt/Imam", "Bittgebet der Gläubiger einholen, wo möglich"],
    documents: ["Schuldenliste", "Quittungen", "Verträge", "Botschaft an Familie zur Abwicklung"],
    safeStorage: "Im Ordner, Vertrauensperson informiert — sensibel, aber notwendig.",
    tellFamily: "Dass offene Schulden und Amanah dokumentiert sind und fachlich (Anwalt/Imam) geklärt werden sollen — Ehrlichkeit wichtiger als Ansehen.",
    commonMistakes: ["Schulden verschweigen", "Nur 'habe keine'", "Kein Plan für Rückzahlung", "Geliehene Sachen nicht dokumentiert"],
    nextStepLabel: "Schulden & Amanah erfassen",
    nextStepHref: "/dashboard/schulden-amanah",
  }, ["quran-nisa-4-11", "quran-nisa-4-12", "hadith-debts-deceased"]),
  topic("w-digital", "digitaler-nachlass", "Digitaler Nachlass", "Konten, Passwörter, Cloud — ohne Plan sind Fotos, Geld und Botschaften verloren.", "digital", {
    whyImportant: "Bank, E-Mail, WhatsApp, Krypto, Fotos — deine Familie braucht Zugang, aber datenschutzrechtlich ist das ohne Vorbereitung oft blockiert.",
    ifMissing: "Gelöschte Konten, gesperrte Handys, verlorene Erinnerungen, offene Abos, Identitätsmissbrauch.",
    prepareItems: ["Liste aller wichtigen Konten", "Passwort-Manager oder versiegelter Umschlag", "2FA-Backup-Codes", "Anweisung: löschen vs. behalten", "Krypto-Wallets dokumentieren"],
    documents: ["Kontenliste", "Zugangsanweisung (nicht alle Passwörter unverschlüsselt!)", "Vollmacht digitaler Nachlass prüfen"],
    safeStorage: "Getrennt vom Alltags-PC, physisch versiegelt oder Passwort-Manager mit Notfallzugang.",
    tellFamily: "Dass es eine Anleitung gibt, wo sie sie finden, und dass sie nicht raten sollen.",
    commonMistakes: ["Passwörter im Klartext in E-Mails", "Gar nichts vorbereitet", "Nur ein Gerät ohne Backup"],
    nextStepLabel: "Digitalen Nachlass erfassen",
    nextStepHref: "/dashboard/digitaler-nachlass",
  }),
  topic("w-sadaqa", "sadaqa-jariya", "Sadaqa Jariya", "Gutes, das nach deinem Tod weiterläuft — bewusst planen, nicht dem Zufall überlassen.", "sadaqa", {
    whyImportant: "Sadaqa Jariya ist eine der wenigen Taten, die im Barzakh weiterwirken können. Viele Muslime wollen Moschee, Brunnen, Bildung — aber ohne Plan passiert nichts.",
    ifMissing: "Familie organisiert teure Trauerfeiern statt anhaltender Sadaqa, deine Wünsche gehen verloren.",
    prepareItems: ["Projekte wählen (Moschee, Brunnen, Bildung, Quran)", "Budget festlegen", "Vertrauensperson für Ausführung", "Dauerhafte Spende vs. einmalig", "Organisationen prüfen"],
    documents: ["Schriftliche Sadaqa-Wünsche", "Spendenquittungen-Vorlage", "Kontakt Organisation"],
    safeStorage: "Im Ordner + Vertrauensperson.",
    tellFamily: "Lieber Sadaqa Jariya als teure kulturelle Rituale — konkrete Projekte nennen.",
    commonMistakes: ["Nur allgemein 'spendet'", "Kein Budget", "Keine vertrauenswürdige Ausführung"],
    nextStepLabel: "Sadaqa Jariya planen",
    nextStepHref: "/dashboard/sadaqa-jariya",
  }, ["hadith-sadaqa-jariya", "quran-barzakh"]),
  topic("w-familie", "familiengespraech", "Familiengespräch", "Der schwerste Moment ist leichter, wenn ihr vorher gesprochen habt.", "familie", {
    whyImportant: "Dokumente allein reichen nicht. Wenn deine Familie zum ersten Mal im Krankenhaus oder beim Bestatter deine Wünsche hört, ist der Schock zu groß.",
    ifMissing: "Missverständnisse, Schuldgefühle, teure Fehlentscheidungen, Brüche in der Familie.",
    prepareItems: ["Termin für ruhiges Gespräch", "Kernpunkte: Notfall, Janazah, Erbe, Schulden", "Brief als Ergänzung", "Vertrauensperson einbeziehen", "Gesprächsleitfaden nutzen"],
    documents: ["Familienbrief", "WhatsApp-Entwurf für später", "Gesprächsleitfaden"],
    safeStorage: "Ordner + Brief ausgedruckt optional.",
    tellFamily: "Dass es kein Abschied vom Leben ist, sondern Entlastung — und dass Fragen erlaubt sind.",
    commonMistakes: ["Alles verstecken bis zum Schluss", "Nur Streit ohne Klarheit", "Keine Vertrauensperson außerhalb der Familie"],
    nextStepLabel: "Familienbrief & Gespräch",
    nextStepHref: "/dashboard/familiengespraech",
  }),
  topic("w-notfall", "notfallkarte", "Notfallkarte", "Rettungskräfte und Familie brauchen in Sekunden die richtigen Infos.", "notfallkarte", {
    whyImportant: "Im Notfall zählt jede Minute. Name, Kontakt, Allergien, Vollmacht-Inhaber — ohne Karte greifen Fremde auf leere Taschen.",
    ifMissing: "Familie erfährt zu spät, falsche Behandlung, niemand weiß wer entscheiden darf.",
    prepareItems: ["Notfallkontakt 1 & 2", "Blutgruppe/Allergien falls bekannt", "Hinweis auf Patientenverfügung", "Sprache der Angehörigen", "Moschee/Imam optional"],
    documents: ["Notfallkarte (ausdruckbar)", "Patientenverfügung-Verweis", "Vollmacht-Verweis"],
    safeStorage: "Geldbörse, Handy-Hintergrund, Kühlschrank, Auto.",
    tellFamily: "Dass sie auf der Karte stehen und sofort erreichbar sein sollen.",
    commonMistakes: ["Veraltete Telefonnummer", "Nur ein Kontakt", "Kein Ausdruck"],
    nextStepLabel: "Notfallkarte erstellen",
    nextStepHref: "/dashboard/notfallkarte",
  }),
];
