import type { KnowledgeArticle } from "@/lib/types";

function topic(
  id: string,
  slug: string,
  title: string,
  summary: string,
  category: string,
  details: NonNullable<KnowledgeArticle["details"]>,
  sourceIds: string[] = []
): KnowledgeArticle {
  return {
    id,
    slug,
    title,
    summary,
    content: details.whyImportant,
    sourceIds,
    reviewStatus: "needs_scholar_review",
    category,
    details,
  };
}

export const wissenTopics: KnowledgeArticle[] = [
  topic(
    "w-janazah",
    "janazah-wuensche",
    "Janazah-Wünsche",
    "Deine Bestattungswünsche sind eine Amanah — dokumentiere sie, bevor andere ratlos sind.",
    "janazah",
    {
      whyImportant:
        "Janazah ist die letzte gemeinschaftliche Pflicht deiner Familie dir gegenüber. Persönliche Wünsche (Beisetzung, Kontakte, Kosten) sind keine allgemeine Fiqh-Regel — sie müssen schriftlich festgehalten werden.",
      ifMissing:
        "Verzögerungen, Streit über Überführung vs. Beisetzung, falsche Kontakte, teure Zusatzleistungen. Die Familie fühlt sich schuldig, obwohl sie ratlos war.",
      prepareItems: [
        "Beisetzung in Deutschland oder Überführung ins Herkunftsland festlegen",
        "Bevorzugten Bestatter und Moschee/Imam-Kontakt notieren",
        "Ghusl-Wünsche klären (wer darf waschen)",
        "Janazah-Gebet: Ort und Imam",
        "Budget und Zahlung klären",
      ],
      todayActions: [
        "Bestatter und Moschee telefonisch anfragen",
        "Schriftliche Janazah-Wünsche anfangen",
        "Vertrauensperson benennen, die den Bestatter anruft",
      ],
      documents: ["Schriftliche Janazah-Wünsche", "Bestatter-Kontakt", "Reisepass-Kopien bei Überführungswunsch"],
      safeStorage: "In Mein Wille + Ausdruck beim Bestatter und bei Vertrauensperson.",
      tellFamily: "Wo der Ordner liegt, wer den Bestatter anruft, dass islamische Grundsätze Vorrang haben.",
      commonMistakes: ["Mündliche Absprachen ohne Dokument", "Kein Bestatter-Kontakt in Deutschland", "Wünsche erst im Sterbebett"],
      nextStepLabel: "Janazah-Wünsche jetzt festhalten",
      nextStepHref: "/dashboard/janazah",
      janazahChecklist: [
        "Totenfürsorge-Nummer / Bestatter 24/7 notiert",
        "Moschee/Imam für Janazah-Gebet kontaktiert",
        "Ghusl-Verantwortliche geklärt",
        "Beisetzungsort (DE oder Überführung) entschieden",
        "Kosten und Zahlung geklärt",
        "Familie weiß, wo das Dokument liegt",
      ],
    },
    ["hadith-janazah-hasten", "hadith-bukhari-janazah-1254", "hadith-bukhari-janazah-1273"]
  ),
  topic("w-ghusl", "ghusl-kafan", "Ghusl & Kafan", "Totenwaschung und Leichentuch sind zentrale islamische Rituale — plane sie konkret.", "ghusl-kafan", {
    whyImportant: "Ghusl und Kafan sind Teil der Würde des Verstorbenen. In Deutschland übernehmen oft Moschee, Bestatter oder Familie — wer was darf, muss vorher geklärt sein.",
    ifMissing: "Falsche Personen waschen, Verzögerung, familiäre Konflikte über Geschlechterregeln.",
    prepareItems: ["Wer Ghusl durchführen soll (gleichgeschlechtlich, muslimisch)", "Ob Moschee/Bestatter übernimmt", "Kafan-Material beschaffen", "Kontakt für Notfall nachts/Wochenende"],
    todayActions: ["Moschee anrufen und Ghusl-Ablauf klären", "Kafan-Beschaffung prüfen", "Wünsche schriftlich festhalten"],
    documents: ["Schriftliche Ghusl/Kafan-Wünsche", "Moschee-Kontakt"],
    legalNotes: ["In Deutschland regelt das Bestattungsgesetz des Bundeslandes den Ablauf — islamische Wünsche mit Bestatter abstimmen."],
    safeStorage: "Mein Wille + Kopie bei Moschee/Bestatter.",
    tellFamily: "Dass Ghusl islamisch prioritär ist und wer angerufen wird.",
    commonMistakes: ["Keine Klärung bei Meinungsunterschieden", "Kafan nicht vorab organisiert"],
    nextStepLabel: "Ghusl & Kafan dokumentieren",
    nextStepHref: "/dashboard/ghusl-kafan",
  }, ["fiqh-ghusl-kafan"]),
  topic("w-bestattung", "bestattung-ueberfuehrung", "Bestattung & Überführung", "Deutschland oder Heimat — beides braucht Vorplanung, Geld und klare Vollmachten.", "bestattung", {
    whyImportant: "Rechtliche Fristen, Kosten, Visa und Familienmeinungen kollidieren oft innerhalb von 48 Stunden nach dem Tod.",
    ifMissing: "Teure Eil-Überführung, Streit zwischen Geschwistern, Verzögerung der Janazah.",
    prepareItems: ["Entscheidung: Beisetzung DE vs. Überführung", "Kostenrahmen und wer zahlt", "Muslimischer Friedhof recherchieren", "Reise-/Rückführungsversicherung prüfen"],
    todayActions: ["Friedhof und Bestattungskosten recherchieren", "Versicherung prüfen", "Entscheidung schriftlich festhalten"],
    documents: ["Bestattungsvorsorgevertrag optional", "Reisepass-Kopien", "Vollmacht für Vertrauensperson"],
    legalNotes: [
      "Bestattungsfristen richten sich nach dem Bestattungsgesetz des Bundeslandes.",
      "Überführungen ins Ausland erfordern konsularische Dokumente — frühzeitig informieren.",
    ],
    safeStorage: "Ordner physisch + digital, Vertrauensperson informiert.",
    tellFamily: "Klare Entscheidung, Budget-Rahmen, wer unterschreibt.",
    commonMistakes: ["Kein Geld für Überführung", "Nur mündlich 'nach Hause'", "Kein Friedhof recherchiert"],
    nextStepLabel: "Bestattungswünsche festhalten",
    nextStepHref: "/dashboard/bestattung",
  }),
  topic(
    "w-pv",
    "patientenverfuegung",
    "Patientenverfügung",
    "Ein deutsches Dokument — legt fest, welche medizinischen Maßnahmen du wünschst oder ablehnst.",
    "patientenverfuegung",
    {
      whyImportant:
        "Die Patientenverfügung ist ein deutsches Rechtsinstrument — keine islamische Spezialquelle. Ohne sie greifen Krankenhaus-Standards. Muslime können darin medizinische Wünsche festhalten und mit Ärzten besprechen.",
      ifMissing: "Unerwünschte Maßnahmen, Familie ohne Stimme, Konflikte zwischen Ärzten und Angehörigen.",
      prepareItems: [
        "Behandlungen ablehnen oder wünschen — mit Arzt besprechen",
        "Organspende-Haltung klären (deutsches Recht)",
        "Aktualisierung alle 2–3 Jahre",
      ],
      todayActions: [
        "BMG-Muster oder Verbraucherzentrale-Tool nutzen",
        "Unterschriebenes Dokument ausdrucken",
        "Kopie an Vertrauensperson und Hausarzt geben",
      ],
      documents: ["Patientenverfügung (schriftlich, unterschrieben)", "Kopie für Vorsorgevollmacht-Inhaber", "Kopie in Notfallmappe"],
      legalNotes: [
        "Rechtsgrundlage: § 1901a BGB — wirksam bei konkreten Behandlungssituationen.",
        "BMG bietet offizielle Textbausteine.",
        "Verbraucherzentrale: Muster und Beratung.",
        "Upload/Ablage des unterschriebenen Dokuments in Mein Wille vorbereiten.",
      ],
      safeStorage: "Notfallmappe, Foto beim Vertrauensmenschen, ggf. Arztakte.",
      tellFamily: "Dass die Patientenverfügung existiert und wo sie liegt.",
      commonMistakes: ["Internet-Vorlage ohne Anpassung", "Veraltete Version", "Keine Kopie im Krankenfall"],
      nextStepLabel: "Medizinische Wünsche dokumentieren",
      nextStepHref: "/dashboard/krankheit",
    },
    ["official-patientenverfuegung-bmj", "official-patientenverfuegung-vz"]
  ),
  topic(
    "w-vollmacht",
    "vorsorgevollmacht",
    "Vorsorgevollmacht",
    "Wer darf für dich unterschreiben, wenn du es nicht kannst?",
    "vorsorgevollmacht",
    {
      whyImportant:
        "Ohne Vorsorgevollmacht kann selbst dein Ehepartner in vielen Bereichen nicht allein handeln. Das deutsche Ehegattennotvertretungsrecht (§ 1358 BGB) ist begrenzt — für Bank, Wohnung und umfassende Entscheidungen brauchst du eine schriftliche Vollmacht.",
      ifMissing: "Betreuungsgericht muss einspringen, Verzögerung, hohe Kosten.",
      prepareItems: [
        "Hauptperson (Bevollmächtigter) benennen",
        "Ersatzperson festlegen — keine automatische Rangfolge der Kinder",
        "Umfang: Gesundheit, Finanzen, Wohnung",
        "Notarielle Beglaubigung bei umfassenden Vollmachten prüfen",
      ],
      todayActions: [
        "Haupt- und Ersatzperson ansprechen",
        "BMJV-Muster prüfen",
        "Vollmacht schriftlich vorbereiten und unterschreiben lassen",
      ],
      documents: ["Vorsorgevollmacht", "Kopie Personalausweis der Bevollmächtigten"],
      legalNotes: [
        "§ 1358 BGB: Ehegatten vertreten einander nur in bestimmten Alltagsangelegenheiten — nicht pauschal für alle Entscheidungen.",
        "Kinder haben keine automatische Entscheidungsrangfolge ohne Vollmacht.",
        "BMJV: offizielle Informationen zur Vorsorgevollmacht.",
      ],
      safeStorage: "Original sicher, Kopien bei Bevollmächtigten.",
      tellFamily: "Wer bevollmächtigt ist und was die Person darf.",
      commonMistakes: ["Nur mündlich 'du entscheidest'", "Keine Ersatzperson", "Vollmacht zu alt"],
      nextStepLabel: "Vorsorgevollmacht vorbereiten",
      nextStepHref: "/dashboard/vollmacht",
    },
    ["official-vorsorgevollmacht"]
  ),
  topic("w-betreuung", "betreuungsverfuegung", "Betreuungsverfügung", "Du kannst mitbestimmen, wer Betreuer wird — sonst entscheidet das Gericht.", "betreuung", {
    whyImportant: "Bei dauerhafter Entscheidungsunfähigkeit ohne Vorsorge greift deutsches Betreuungsrecht. Eine Betreuungsverfügung gibt dir Mitsprache.",
    ifMissing: "Fremde Betreuung, Verzögerung, Familie außen vor.",
    prepareItems: ["Wunschperson für Betreuung", "Ausgeschlossene Personen benennen", "Abstimmung mit Vorsorgevollmacht"],
    todayActions: ["Betreuungsverfügung-Muster prüfen", "Wunschperson informieren"],
    documents: ["Betreuungsverfügung"],
    legalNotes: ["Betreuungsverfügung nach § 1896 BGB — Gericht berücksichtigt deinen Wunsch, wenn zumutbar."],
    safeStorage: "Mit Vorsorgeunterlagen.",
    tellFamily: "Dass du jemanden vorgeschlagen hast.",
    commonMistakes: ["Verwechslung mit Patientenverfügung"],
    nextStepLabel: "Betreuungswünsche festhalten",
    nextStepHref: "/dashboard/betreuung",
  }),
  topic(
    "w-testament",
    "testament-erbe",
    "Testament & Erbe",
    "Islamisches Erbe und deutsches Erbrecht — Wasiyyah und feste Erbanteile klar unterscheiden.",
    "testament",
    {
      whyImportant:
        "Allah hat Erbteile im Qur'an festgelegt. Wasiyyah (freie Verfügung bis max. 1/3) ist davon zu unterscheiden. In Deutschland brauchst du oft ein Testament/Erbvertrag — das ist Angelegenheit für Anwalt und Imam, nicht für Selbstinterpretation.",
      ifMissing: "Streit unter Erben, Rechtsunsicherheit, Vermögen verteilt ohne Plan.",
      prepareItems: [
        "Vermögensübersicht erstellen",
        "Erben nach islamischem Recht listen — fachlich prüfen",
        "Wasiyyah (max. 1/3) von festen Erbanteilen trennen",
        "Schulden vor Verteilung bedenken",
      ],
      todayActions: ["Vermögensliste anfangen", "Termin mit Anwalt/Imam planen", "Schulden dokumentieren"],
      documents: ["Testament/Erbvertrag", "Vermögensliste", "Schuldenliste"],
      legalNotes: [
        "Deutsches Pflichtteilsrecht kann mit islamischer Verteilung kollidieren — Fachberatung nötig.",
        "Kein Erbrechner in dieser App — nur Orientierung.",
      ],
      safeStorage: "Notar/Safe + Vertrauensperson informiert.",
      tellFamily: "Dass ein Plan existiert und fachliche Hilfe nötig ist.",
      commonMistakes: ["Haus 'schenken' ohne Erbplan", "Wasiyyah über 1/3", "Kein Testamentsentwurf"],
      nextStepLabel: "Erbe & Testament vorbereiten",
      nextStepHref: "/dashboard/testament",
    },
    ["quran-nisa-4-11", "quran-nisa-4-12", "quran-nisa-4-176", "hadith-wasiyyah-third", "hadith-wasiyyah-saad"]
  ),
  topic("w-schulden", "schulden-amanah", "Schulden & Amanah", "Unbezahlte Schulden und anvertraute Güter sind eine Amanah.", "schulden", {
    whyImportant: "Offene Schulden und anvertraute Güter können Familie belasten. Die Überlieferung verdeutlicht die Ernsthaftigkeit — ohne individuelle Rechtsregel.",
    ifMissing: "Familie zahlt aus Unwissenheit, Streit, verlorenes Vertrauen.",
    prepareItems: ["Alle Schulden listen", "An wen, Betrag, Frist", "Amanah: anvertraute Werte dokumentieren"],
    todayActions: ["Schuldenliste beginnen", "Vertrauensperson informieren"],
    documents: ["Schuldenliste", "Quittungen", "Verträge"],
    safeStorage: "Im Ordner — sensibel, aber notwendig.",
    tellFamily: "Dass Schulden dokumentiert sind und fachlich geklärt werden sollen.",
    commonMistakes: ["Schulden verschweigen", "Kein Plan für Rückzahlung"],
    nextStepLabel: "Schulden & Amanah erfassen",
    nextStepHref: "/dashboard/schulden-amanah",
  }, ["quran-nisa-4-11", "quran-nisa-4-12", "hadith-debts-deceased"]),
  topic("w-digital", "digitaler-nachlass", "Digitaler Nachlass", "Konten, Passwörter, Cloud — ohne Plan sind Fotos, Geld und Botschaften verloren.", "digital", {
    whyImportant: "Bank, E-Mail, WhatsApp — deine Familie braucht Zugang, aber datenschutzrechtlich ist das ohne Vorbereitung oft blockiert.",
    ifMissing: "Gelöschte Konten, gesperrte Handys, verlorene Erinnerungen.",
    prepareItems: ["Liste wichtiger Konten", "Passwort-Manager oder versiegelter Umschlag", "2FA-Backup-Codes", "Anweisung: löschen vs. behalten"],
    todayActions: ["Kontenliste anlegen", "Notfallzugang für Passwort-Manager einrichten"],
    documents: ["Kontenliste", "Zugangsanweisung (keine Klartext-Passwörter per E-Mail)"],
    legalNotes: ["Digitale Vorsorgevollmacht und Nutzungsbedingungen der Anbieter prüfen."],
    safeStorage: "Getrennt vom Alltags-PC, physisch versiegelt.",
    tellFamily: "Dass es eine Anleitung gibt und wo sie liegt.",
    commonMistakes: ["Passwörter im Klartext in E-Mails", "Gar nichts vorbereitet"],
    nextStepLabel: "Digitalen Nachlass erfassen",
    nextStepHref: "/dashboard/digitaler-nachlass",
  }),
  topic(
    "w-sadaqa",
    "sadaqa-jariya",
    "Sadaqa Jariya",
    "Gutes, das nach deinem Tod weiterwirken kann — bewusst planen.",
    "sadaqa",
    {
      whyImportant:
        "Sadaqa Jariya ist in der authentischen Überlieferung genannt — ohne Garantie über individuelles Schicksal. Plane konkrete Projekte statt teurer Trauerfeiern.",
      ifMissing: "Familie organisiert teure Rituale statt anhaltender Sadaqa.",
      prepareItems: ["Projekte wählen (Bildung, Brunnen, Moschee)", "Budget festlegen", "Vertrauensperson für Ausführung"],
      todayActions: ["Projekt auswählen", "Budget notieren", "Partnerorganisation prüfen"],
      documents: ["Schriftliche Sadaqa-Wünsche", "Spendenquittungen-Vorlage"],
      safeStorage: "Im Ordner + Vertrauensperson.",
      tellFamily: "Konkrete Projekte statt allgemeines 'spendet'.",
      commonMistakes: ["Nur allgemein 'spendet'", "Kein Budget", "Keine vertrauenswürdige Ausführung"],
      nextStepLabel: "Sadaqa Jariya planen",
      nextStepHref: "/dashboard/sadaqa-jariya",
    },
    ["hadith-sadaqa-jariya", "quran-al-muminun-23-99", "partner-gemeinsam1-sadaqa"]
  ),
  topic("w-familie", "familiengespraech", "Familiengespräch", "Der schwerste Moment ist leichter, wenn ihr vorher gesprochen habt.", "familie", {
    whyImportant: "Dokumente allein reichen nicht. Ein ruhiges Gespräch entlastet die Familie im Ernstfall.",
    ifMissing: "Missverständnisse, Schuldgefühle, teure Fehlentscheidungen.",
    prepareItems: ["Termin für ruhiges Gespräch", "Kernpunkte: Notfall, Janazah, Erbe", "Brief als Ergänzung"],
    todayActions: ["Gesprächstermin vorschlagen", "Kernpunkte aufschreiben"],
    documents: ["Familienbrief", "Gesprächsleitfaden"],
    safeStorage: "Ordner + Brief optional ausgedruckt.",
    tellFamily: "Dass es kein Abschied vom Leben ist, sondern Entlastung.",
    commonMistakes: ["Alles verstecken bis zum Schluss", "Keine Vertrauensperson"],
    nextStepLabel: "Familienbrief & Gespräch",
    nextStepHref: "/dashboard/familiengespraech",
  }, ["quran-ash-shura-42-38"]),
  topic("w-notfall", "notfallkarte", "Notfallkarte", "Rettungskräfte und Familie brauchen in Sekunden die richtigen Infos.", "notfallkarte", {
    whyImportant: "Im Notfall zählt jede Minute. Name, Kontakt, Allergien, Vollmacht-Inhaber — ohne Karte greifen Fremde auf leere Taschen.",
    ifMissing: "Familie erfährt zu spät, falsche Behandlung.",
    prepareItems: ["Notfallkontakt 1 & 2", "Allergien falls bekannt", "Hinweis auf Patientenverfügung", "Vollmacht-Verweis"],
    todayActions: ["Notfallkarte aus Mein Wille drucken", "Kontaktnummern prüfen"],
    documents: ["Notfallkarte", "Patientenverfügung-Verweis"],
    safeStorage: "Geldbörse, Handy-Hintergrund, Kühlschrank.",
    tellFamily: "Dass sie auf der Karte stehen und erreichbar sein sollen.",
    commonMistakes: ["Veraltete Telefonnummer", "Kein Ausdruck"],
    nextStepLabel: "Notfallkarte erstellen",
    nextStepHref: "/dashboard/notfallkarte",
  }),
  topic(
    "w-barzakh",
    "barzakh",
    "Barzakh",
    "Der Zwischenzustand bis zur Auferstehung — nur sichere Qur'anstellen, keine Spekulation.",
    "barzakh",
    {
      whyImportant:
        "Barzakh ist im Qur'an erwähnt — Details des Verborgenen sind nicht Gegenstand dieser App. Vorsorge betrifft das Handeln im Leben, nicht Spekulation über das Jenseits.",
      ifMissing: "Familie trifft Entscheidungen ohne geistige Vorbereitung — aber ohne falsche Gewissheiten.",
      prepareItems: ["Gutes vorausschicken durch Taten und Dua", "Sadaqa Jariya planen", "Familie über islamische Grundhaltung informieren"],
      todayActions: ["Sadaqa Jariya-Wünsche festhalten", "Familienbrief mit spirituellen Wünschen (ohne Spekulation)"],
      documents: ["Schriftliche Wünsche für anhaltende Taten"],
      safeStorage: "Im Ordner bei Vertrauensperson.",
      tellFamily: "Dass Bittgebete und Sadaqa helfen können — ohne Garantieversprechen.",
      commonMistakes: ["Spekulation über Details des Barzakh", "Kulturelle Mythen als Islam darstellen"],
      nextStepLabel: "Akhira-Vorsorge festhalten",
      nextStepHref: "/dashboard/sadaqa-jariya",
    },
    ["quran-al-muminun-23-99", "quran-al-imran-3-185"]
  ),
  topic(
    "w-akhira",
    "akhira-vorsorge",
    "Akhira-Vorsorge",
    "Vorbereitung auf das Jenseits durch Taten heute — ohne Garantien oder Spekulation.",
    "akhira",
    {
      whyImportant:
        "Akhira bezeichnet das Jenseits. Der Qur'an erinnert an die Endlichkeit des Lebens — Vorsorge bedeutet, heute Gutes zu tun und zu dokumentieren, nicht über das Verborgene zu spekulieren.",
      ifMissing: "Familie organisiert teure Rituale ohne geplante Sadaqa oder Wissensweitergabe.",
      prepareItems: ["Sadaqa Jariya-Projekte wählen", "Nützliches Wissen dokumentieren", "Bittgebete und Dua-Wünsche festhalten"],
      todayActions: ["Sadaqa-Projekt wählen", "Familie über Wünsche informieren"],
      documents: ["Sadaqa-Wünsche", "Familienbrief"],
      safeStorage: "Ordner + Vertrauensperson.",
      tellFamily: "Konkrete Projekte statt allgemeiner Absichten.",
      commonMistakes: ["Spekulative Versprechen über Belohnung", "Sura al-Mulk als garantierter Schutzvers — nicht belegen"],
      nextStepLabel: "Akhira-Wünsche dokumentieren",
      nextStepHref: "/dashboard/sadaqa-jariya",
    },
    ["quran-al-imran-3-185", "quran-al-hashr-59-18", "hadith-sadaqa-jariya"]
  ),
];

export function getWissenTopicBySlug(slug: string): KnowledgeArticle | undefined {
  return wissenTopics.find((t) => t.slug === slug);
}
