import type { ModuleConfig } from "@/lib/types";

export const moduleConfigs: ModuleConfig[] = [
  {
    id: "notfallkarte",
    title: "Notfallkarte",
    description: "Wichtige Infos für den Notfall — immer griffbereit.",
    icon: "🆘",
    path: "/dashboard/notfallkarte",
    criticalFields: ["emergencyCard.name", "emergencyCard.emergencyContact1.name", "emergencyCard.emergencyContact1.phone"],
    requiredFields: ["emergencyCard.name", "emergencyCard.emergencyContact1.name", "emergencyCard.emergencyContact1.phone"],
    warningFields: ["emergencyCard.familyDoctor", "emergencyCard.medications"],
  },
  {
    id: "krankheit",
    title: "Krankheit & Patientenverfügung",
    description: "Medizinische und religiöse Wünsche dokumentieren.",
    icon: "🏥",
    path: "/dashboard/krankheit",
    criticalFields: ["medicalWishes.medicalWishes", "medicalWishes.religiousWishes"],
  },
  {
    id: "vollmacht",
    title: "Vorsorgevollmacht",
    description: "Wer darf im Namen handeln?",
    icon: "📋",
    path: "/dashboard/vollmacht",
    criticalFields: ["powerOfAttorney.authorizedPerson"],
  },
  {
    id: "betreuung",
    title: "Betreuungsverfügung",
    description: "Gewünschter und unerwünschter Betreuer.",
    icon: "🤝",
    path: "/dashboard/betreuung",
    criticalFields: ["careDirective.preferredGuardian"],
  },
  {
    id: "janazah",
    title: "Janazah-Wünsche",
    description: "Islamische Bestattungswünsche festhalten.",
    icon: "🕌",
    path: "/dashboard/janazah",
    criticalFields: ["janazahWishes.islamicBurialDesired", "janazahWishes.preferredFuneralDirector"],
  },
  {
    id: "ghusl-kafan",
    title: "Ghusl & Kafan",
    description: "Waschung und Leichentuch — Würde und Wünsche.",
    icon: "🤍",
    path: "/dashboard/ghusl-kafan",
    criticalFields: ["ghuslKafan.whoMayBePresent"],
  },
  {
    id: "bestattung",
    title: "Bestattung / Überführung",
    description: "Deutschland oder Heimat — Kriterien festlegen.",
    icon: "🌍",
    path: "/dashboard/bestattung",
    criticalFields: ["burialPreference.cityPlz"],
  },
  {
    id: "testament",
    title: "Testament & Erbe",
    description: "Farāʾiḍ, Waṣiyya und Ampelcheck.",
    icon: "📜",
    path: "/dashboard/testament",
    criticalFields: ["inheritanceProfile.married", "inheritanceProfile.sons", "inheritanceProfile.daughters"],
  },
  {
    id: "schulden-amanah",
    title: "Schulden & Amanah",
    description: "Offene Rechte und Pflichten ordnen.",
    icon: "⚖️",
    path: "/dashboard/schulden-amanah",
    criticalFields: ["debtsAmanah"],
  },
  {
    id: "digitaler-nachlass",
    title: "Digitaler Nachlass",
    description: "Hinweise zu Konten — keine Passwörter.",
    icon: "💻",
    path: "/dashboard/digitaler-nachlass",
    criticalFields: ["digitalLegacy"],
  },
  {
    id: "barzakh",
    title: "Barzakh-Plan",
    description: "Vorbereitung für die Zeit nach dem Tod.",
    icon: "🌙",
    path: "/dashboard/barzakh",
    criticalFields: ["barzakhPlan.familyFirstCheck"],
  },
  {
    id: "sadaqa-jariya",
    title: "Sadaqa Jariya",
    description: "Das Gute, das nach dir bleibt.",
    icon: "💚",
    path: "/dashboard/sadaqa-jariya",
    criticalFields: ["sadaqaJariya.preferredPot"],
  },
  {
    id: "familie",
    title: "Familiengespräch",
    description: "Brief, WhatsApp und Gesprächsleitfaden.",
    icon: "👨‍👩‍👧‍👦",
    path: "/dashboard/familie",
    criticalFields: ["familyMessage.familyLetter"],
  },
];

export const startPaths = [
  { id: "krankheit", title: "Ich möchte für Krankheit und Krankenhaus vorsorgen", icon: "🏥", path: "/dashboard/krankheit" },
  { id: "janazah", title: "Ich möchte meine Janazah und Bestattung vorbereiten", icon: "🕌", path: "/dashboard/janazah" },
  { id: "testament", title: "Ich möchte Testament und islamisches Erbe verstehen", icon: "📜", path: "/dashboard/testament" },
  { id: "schulden-amanah", title: "Ich möchte Schulden, Amanah und offene Rechte ordnen", icon: "⚖️", path: "/dashboard/schulden-amanah" },
  { id: "barzakh", title: "Ich möchte Barzakh und Sadaqa Jariya vorbereiten", icon: "🌙", path: "/dashboard/barzakh" },
  { id: "familie", title: "Ich möchte meine Familie informieren", icon: "👨‍👩‍👧‍👦", path: "/dashboard/familie" },
  { id: "emergency", title: "Ich habe einen akuten Todesfall", icon: "🆘", path: "/akuter-todesfall" },
  { id: "complete", title: "Ich möchte den kompletten AmanahOrdner erstellen", icon: "📁", path: "/dashboard" },
];
