import { SCHEMA_VERSION } from "./schema";
import type { AmanahOrdnerData } from "./types";

export const defaultAmanahData: AmanahOrdnerData = {
  schemaVersion: SCHEMA_VERSION,
  userProfile: { name: "", birthDate: "", language: "de" },
  familyMembers: [],
  emergencyCard: {
    name: "",
    birthDate: "",
    emergencyContact1: { name: "", phone: "", relation: "" },
    emergencyContact2: { name: "", phone: "", relation: "" },
    familyDoctor: "",
    illnesses: "",
    medications: "",
    allergies: "",
    language: "Deutsch",
    mosqueImam: "",
    preferredFuneralDirector: "",
    hasPatientenverfuegung: null,
    hasVorsorgevollmacht: null,
    hasJanazahWishes: null,
  },
  medicalWishes: {
    medicalWishes: "",
    religiousWishes: "",
    imamSeelsorge: "",
    dignityBoundaries: "",
    whoSpeaksToDoctors: "",
    documentLocation: "",
    openQuestionsDoctor: "",
    openQuestionsLawyer: "",
    openQuestionsImam: "",
  },
  powerOfAttorney: {
    authorizedPerson: "",
    substitutePerson: "",
    medical: "",
    authorities: "",
    bank: "",
    housing: "",
    care: "",
    burial: "",
    documents: "",
    digitalAccounts: "",
    excludedPersons: "",
  },
  careDirective: {
    preferredGuardian: "",
    excludedGuardian: "",
    religiousWishes: "",
    careHousingWishes: "",
    languageFamilyNotes: "",
  },
  janazahWishes: {
    islamicBurialDesired: null,
    noUnnecessaryDelay: null,
    ghusl: "",
    kafan: "",
    janazahPrayer: "",
    burialGermany: null,
    repatriation: "",
    preferredCemetery: "",
    preferredMosque: "",
    preferredFuneralDirector: "",
    culturalExclusions: "",
    messageToFamily: "",
  },
  ghuslKafan: {
    whoMayBePresent: "",
    preferredGhuslTeam: "",
    dignityBoundaries: "",
    spouseNote: "",
    familyFarewell: "",
    familyFarewellConditions: "",
    notes: "",
  },
  burialPreference: {
    burialGermanyPreferred: null,
    repatriationPreferred: null,
    decisionCriteria: "",
    cityPlz: "",
    contactPerson: "",
    costDocumentNotes: "",
    familyNote: "",
  },
  inheritanceProfile: {
    married: null,
    spouseAlive: null,
    sons: 0,
    daughters: 0,
    parentsAlive: null,
    siblings: null,
    stepchildren: null,
    fosterChildren: null,
    nonMuslimRelatives: null,
    realEstate: null,
    companyGmbH: null,
    foreignProperty: null,
    approximateWealth: "",
    debts: "",
    desiredWasiyyah: "",
    desiredSadaqaJariya: "",
    openQuestionsImam: "",
    openQuestionsLawyer: "",
  },
  documents: [],
  assets: [],
  debtsAmanah: [],
  digitalLegacy: [],
  donations: [],
  importantInstructions: [],
  barzakhPlan: {
    familyFirstCheck: "",
    importantDebtsAmanah: "",
    desiredDuas: "",
    desiredSadaqaJariya: "",
    culturalExclusions: "",
    peopleToContact: "",
    messageToFamily: "",
  },
  sadaqaJariya: {
    joinFoerderkreis: null,
    preferredPot: "",
    monthlyAmount: "",
    oneTimeAmount: "",
    personToVerify: "",
    gemeinsam1Link: "",
  },
  familyMessage: {
    familyLetter: "",
    whatsappMessage: "",
    conversationGuide: "",
    keyWishesSummary: "",
  },
  selectedPath: "complete",
  lastSaved: null,
  reviewStatus: "draft",
};
