import { defaultAmanahData } from "./defaults";
import type { AmanahOrdnerData } from "./types";

export const demoAmanahData: AmanahOrdnerData = {
  ...defaultAmanahData,
  userProfile: { name: "Ahmed Demo", birthDate: "1985-03-15", language: "de" },
  familyMembers: [
    { id: "fm-1", name: "Fatima Demo", relation: "Ehepartnerin", phone: "+49 170 1234567" },
    { id: "fm-2", name: "Yusuf Demo", relation: "Sohn", birthDate: "2010-07-22" },
  ],
  emergencyCard: {
    name: "Ahmed Demo",
    birthDate: "1985-03-15",
    emergencyContact1: { name: "Fatima Demo", phone: "+49 170 1234567", relation: "Ehepartnerin" },
    emergencyContact2: { name: "Ali Demo", phone: "+49 171 9876543", relation: "Bruder" },
    familyDoctor: "Dr. Schmidt, Berlin",
    illnesses: "Diabetes Typ 2",
    medications: "Metformin 500mg",
    allergies: "Keine bekannt",
    language: "Deutsch, Türkisch, Arabisch",
    mosqueImam: "Imam Mustafa, Mevlana Moschee Berlin",
    preferredFuneralDirector: "Islamische Bestattungen Berlin",
    hasPatientenverfuegung: true,
    hasVorsorgevollmacht: true,
    hasJanazahWishes: true,
  },
  medicalWishes: {
    medicalWishes: "Keine lebenserhaltenden Maßnahmen bei ausweisloser Hirntod-Diagnose — nach fachlicher Prüfung mit Arzt besprechen.",
    religiousWishes: "Imam-Seelsorge bei schwerer Krankheit wünschenswert.",
    imamSeelsorge: "Imam Mustafa kontaktieren",
    dignityBoundaries: "Keine unnötige Entblößung bei medizinischer Versorgung.",
    whoSpeaksToDoctors: "Fatima Demo (Ehepartnerin)",
    documentLocation: "Ordner im Schreibtisch, obere Schublade",
    openQuestionsDoctor: "",
    openQuestionsLawyer: "Patientenverfügung notariell beglaubigen lassen?",
    openQuestionsImam: "",
  },
  powerOfAttorney: {
    authorizedPerson: "Fatima Demo",
    substitutePerson: "Ali Demo",
    medical: "Ja",
    authorities: "Ja",
    bank: "Ja",
    housing: "Ja",
    care: "Ja",
    burial: "Ja",
    documents: "Ja",
    digitalAccounts: "Hinweise im Passwort-Manager",
    excludedPersons: "",
  },
  janazahWishes: {
    islamicBurialDesired: true,
    noUnnecessaryDelay: true,
    ghusl: "Islamische Waschung nach sunnat",
    kafan: "3 weiße Tücher",
    janazahPrayer: "In der Mevlana Moschee Berlin",
    burialGermany: true,
    repatriation: "no",
    preferredCemetery: "Islamischer Friedhof Gatow, Berlin",
    preferredMosque: "Mevlana Moschee Berlin",
    preferredFuneralDirector: "Islamische Bestattungen Berlin",
    culturalExclusions: "Keine kulturellen Bräuche, die dem Islam widersprechen",
    messageToFamily: "Bitte keine unnötige Verzögerung. Ruhe und Einheit in der Familie.",
  },
  debtsAmanah: [
    {
      id: "debt-1",
      type: "zakat",
      description: "Zakat für Ramadan 2024 noch nicht vollständig entrichtet",
      person: "Zakat-Empfänger (noch festzulegen)",
      priority: "high",
    },
  ],
  digitalLegacy: [
    {
      id: "dig-1",
      type: "password_manager",
      description: "1Password Familienkonto",
      locationHint: "Master-Passwort im Banksafe, Schließfach 42",
    },
  ],
  documents: [
    {
      id: "doc-1",
      type: "patientenverfuegung",
      title: "Patientenverfügung 2024",
      location: "Schreibtisch, Ordner Vorsorge",
      reviewStatus: "needs_scholar_review",
    },
  ],
  donations: [
    {
      id: "don-1",
      type: "sadaqa_jariya",
      description: "Brunnen-Projekt über Gemeinsam1 e.V.",
      amount: "500 EUR",
      recipient: "Gemeinsam1 e.V.",
    },
  ],
  importantInstructions: [
    {
      id: "inst-1",
      category: "religious",
      title: "Janazah-Gebet",
      content: "Janazah-Gebet in der Mevlana Moschee Berlin wünschenswert.",
      priority: "high",
    },
  ],
  inheritanceProfile: {
    ...defaultAmanahData.inheritanceProfile,
    married: true,
    spouseAlive: true,
    sons: 1,
    daughters: 1,
  },
  familyMessage: {
    familyLetter: "Liebe Familie, dieser Ordner ist meine Vorbereitung — bitte mit Imam und Anwalt fachlich prüfen lassen.",
    whatsappMessage: "Meine Vorsorge in Mein Wille liegt im Schreibtisch. Bitte Notfallkontakt Fatima anrufen.",
    conversationGuide: "1. Notfallkontakt informieren\n2. Patientenverfügung zeigen\n3. Imam kontaktieren",
    keyWishesSummary: "Islamische Bestattung in Berlin, keine Verzögerung.",
  },
  selectedPath: "complete",
  reviewStatus: "needs_scholar_review",
};
