import type { GuidedQuestion } from "./types";

export const GUIDED_QUESTION_PLAN: GuidedQuestion[] = [
  {
    id: "gf-ec1-name",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.emergencyContact1.name",
    questionText: "Wer soll im Notfall zuerst kontaktiert werden?",
    helpText: "Name einer Vertrauensperson — Ehepartner, Geschwister oder enge Angehörige.",
    sensitivity: "low",
    expectedAnswerType: "person",
    canSkip: false,
    priority: 1,
    critical: true,
  },
  {
    id: "gf-ec1-phone",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.emergencyContact1.phone",
    questionText: "Wie kann deine Familie diese Person am schnellsten erreichen?",
    helpText: "Telefonnummer mit Vorwahl, z. B. 0176 …",
    sensitivity: "low",
    expectedAnswerType: "phone",
    canSkip: false,
    priority: 2,
    critical: true,
  },
  {
    id: "gf-ec1-relation",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.emergencyContact1.relation",
    questionText: "Welche Beziehung hat diese Person zu dir?",
    helpText: "z. B. Ehefrau, Bruder, Schwester, Freund.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 3,
    critical: false,
  },
  {
    id: "gf-emergency-name",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.name",
    questionText: "Unter welchem Namen sollen Rettungskräfte dich identifizieren?",
    helpText: "Vollständiger Name wie im Ausweis.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 4,
    critical: false,
  },
  {
    id: "gf-doc-location",
    moduleId: "krankheit",
    fieldPath: "medicalWishes.documentLocation",
    questionText: "Wo findet deine Familie wichtige Dokumente?",
    helpText: "Ort oder Hinweis — z. B. Ordner zu Hause, Tresor, Anwalt. Keine Passwörter.",
    sensitivity: "low",
    expectedAnswerType: "location",
    canSkip: true,
    priority: 5,
    critical: true,
  },
  {
    id: "gf-medical-hints",
    moduleId: "krankheit",
    fieldPath: "medicalWishes.medicalWishes",
    questionText: "Gibt es medizinische Hinweise, die deine Familie kennen sollte?",
    helpText: "Nur allgemeine Orientierung — keine Diagnosen. Individuelle Entscheidungen bitte mit Arzt besprechen.",
    sensitivity: "medium",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 6,
    critical: false,
    safetyNotice: "Keine medizinische Beratung — nur dokumentieren, was du mit Arzt besprochen hast.",
  },
  {
    id: "gf-patientenverfuegung",
    moduleId: "krankheit",
    fieldPath: "emergencyCard.hasPatientenverfuegung",
    questionText: "Hast du eine Patientenverfügung — ja oder nein?",
    helpText: "Zur Orientierung. Rechtliche Wirksamkeit bitte fachlich prüfen lassen.",
    sensitivity: "medium",
    expectedAnswerType: "boolean",
    canSkip: true,
    priority: 7,
    critical: true,
    safetyNotice: "Keine Rechtsberatung — nur Status dokumentieren.",
  },
  {
    id: "gf-vollmacht-status",
    moduleId: "vollmacht",
    fieldPath: "emergencyCard.hasVorsorgevollmacht",
    questionText: "Hast du eine Vorsorgevollmacht — ja oder nein?",
    helpText: "Zur Orientierung für deine Familie. Details bitte mit Anwalt/Notar klären.",
    sensitivity: "medium",
    expectedAnswerType: "boolean",
    canSkip: true,
    priority: 8,
    critical: true,
    safetyNotice: "Keine Rechtsberatung.",
  },
  {
    id: "gf-authorized-person",
    moduleId: "vollmacht",
    fieldPath: "powerOfAttorney.authorizedPerson",
    questionText: "Gibt es eine Vertrauensperson, die deine Familie unterstützen soll?",
    helpText: "Name der bevollmächtigten oder vertrauenswürdigen Person — keine Rechtsberatung.",
    sensitivity: "medium",
    expectedAnswerType: "person",
    canSkip: true,
    priority: 9,
    critical: true,
  },
  {
    id: "gf-substitute-person",
    moduleId: "vollmacht",
    fieldPath: "powerOfAttorney.substitutePerson",
    questionText: "Gibt es eine Ersatzperson, falls die erste Person nicht erreichbar ist?",
    helpText: "Optional — Name und kurzer Hinweis.",
    sensitivity: "low",
    expectedAnswerType: "person",
    canSkip: true,
    priority: 10,
    critical: false,
  },
  {
    id: "gf-who-speaks-doctors",
    moduleId: "krankheit",
    fieldPath: "medicalWishes.whoSpeaksToDoctors",
    questionText: "Wer soll im Krankheitsfall mit Ärzten sprechen dürfen?",
    helpText: "Name und Beziehung — zur Vorbereitung, nicht als medizinische Entscheidung.",
    sensitivity: "medium",
    expectedAnswerType: "person",
    canSkip: true,
    priority: 11,
    critical: false,
    safetyNotice: "Keine medizinische Beratung.",
  },
  {
    id: "gf-janazah-director",
    moduleId: "janazah",
    fieldPath: "janazahWishes.preferredFuneralDirector",
    questionText: "Möchtest du festhalten, ob bestimmte Bestattungswünsche bekannt sind?",
    helpText: "Gewünschter Bestatter oder Moschee-Kontakt — allgemeine Orientierung.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 12,
    critical: true,
  },
  {
    id: "gf-janazah-mosque",
    moduleId: "janazah",
    fieldPath: "janazahWishes.preferredMosque",
    questionText: "Welche Moschee oder welcher Imam soll deine Familie kontaktieren?",
    helpText: "Name der Moschee oder des Imams — keine Fatwa.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 13,
    critical: false,
  },
  {
    id: "gf-janazah-burial",
    moduleId: "janazah",
    fieldPath: "janazahWishes.islamicBurialDesired",
    questionText: "Ist dir eine islamische Bestattung wichtig — ja oder nein?",
    helpText: "Zur Orientierung für Angehörige. Detailfragen mit Imam/Gelehrten besprechen.",
    sensitivity: "medium",
    expectedAnswerType: "boolean",
    canSkip: true,
    priority: 14,
    critical: false,
    safetyNotice: "Keine religiöse Fatwa.",
  },
  {
    id: "gf-janazah-message",
    moduleId: "janazah",
    fieldPath: "janazahWishes.messageToFamily",
    questionText: "Gibt es einen kurzen Wunsch zur Bestattung, den deine Familie kennen soll?",
    helpText: "Freitext — z. B. schlichte Janazah, keine aufwendigen Feiern.",
    sensitivity: "low",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 15,
    critical: false,
  },
  {
    id: "gf-digital-accounts",
    moduleId: "digitaler-nachlass",
    fieldPath: "powerOfAttorney.digitalAccounts",
    questionText: "Gibt es digitale Konten, auf die deine Familie achten sollte?",
    helpText: "Nur Hinweise — E-Mail, Cloud, Abos. Keine Passwörter speichern.",
    sensitivity: "low",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 16,
    critical: false,
  },
  {
    id: "gf-debts-hint",
    moduleId: "schulden-amanah",
    fieldPath: "barzakhPlan.importantDebtsAmanah",
    questionText: "Gibt es laufende Verträge, Schulden oder Verpflichtungen, die bekannt sein sollten?",
    helpText: "Kurze Hinweise — z. B. offene Darlehen, Zakat, anvertraute Gegenstände.",
    sensitivity: "medium",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 17,
    critical: false,
  },
  {
    id: "gf-family-doctor",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.familyDoctor",
    questionText: "Wer ist dein Hausarzt oder Ansprechpartner im Gesundheitswesen?",
    helpText: "Name und Praxis — zur Orientierung im Notfall.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 18,
    critical: false,
  },
  {
    id: "gf-allergies",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.allergies",
    questionText: "Gibt es Allergien oder wichtige medizinische Hinweise für Rettungskräfte?",
    helpText: "Nur dokumentieren — keine Diagnose. Bei Unsicherheit Arzt fragen.",
    sensitivity: "medium",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 19,
    critical: false,
    safetyNotice: "Keine medizinische Beratung.",
  },
  {
    id: "gf-burial-contact",
    moduleId: "bestattung",
    fieldPath: "burialPreference.contactPerson",
    questionText: "Wer kann bei Bestattungsfragen als Ansprechpartner dienen?",
    helpText: "Name einer Person, die deine Familie unterstützen kann.",
    sensitivity: "low",
    expectedAnswerType: "person",
    canSkip: true,
    priority: 20,
    critical: false,
  },
  {
    id: "gf-family-letter",
    moduleId: "familie",
    fieldPath: "familyMessage.familyLetter",
    questionText: "Möchtest du eine kurze Nachricht an deine Familie vorbereiten?",
    helpText: "Entwurf — bitte selbst prüfen. Kein automatischer Versand.",
    sensitivity: "low",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 21,
    critical: false,
  },
  {
    id: "gf-key-wishes",
    moduleId: "familie",
    fieldPath: "familyMessage.keyWishesSummary",
    questionText: "Was sind deine drei wichtigsten Wünsche für deine Familie?",
    helpText: "Kurz und verständlich — zur Orientierung.",
    sensitivity: "low",
    expectedAnswerType: "freeform",
    canSkip: true,
    priority: 22,
    critical: false,
  },
  {
    id: "gf-ec2-name",
    moduleId: "notfallkarte",
    fieldPath: "emergencyCard.emergencyContact2.name",
    questionText: "Gibt es einen zweiten Notfallkontakt?",
    helpText: "Optional — Name einer weiteren Vertrauensperson.",
    sensitivity: "low",
    expectedAnswerType: "person",
    canSkip: true,
    priority: 23,
    critical: false,
  },
  {
    id: "gf-user-name",
    moduleId: "notfallkarte",
    fieldPath: "userProfile.name",
    questionText: "Wie möchtest du in deinem AmanahOrdner genannt werden?",
    helpText: "Dein Name für Begrüßung und Dokumente.",
    sensitivity: "low",
    expectedAnswerType: "text",
    canSkip: true,
    priority: 24,
    critical: false,
  },
];

export function getQuestionById(id: string): GuidedQuestion | undefined {
  return GUIDED_QUESTION_PLAN.find((q) => q.id === id);
}

export function getQuestionPlanCount(): number {
  return GUIDED_QUESTION_PLAN.length;
}
